### ISSUE TITLE
why css-in-js

### ISSUE THREAD

**Issue by ZWkang** [ZWkang/kangct#14]
css很重要的几点包括：
- 可读性
- 可维护性
- 可阅读性
- 扩展性

这对于我们编写的代码也是这么一回事。

但是人们编写css的时候很容易broken它们

人们总是习惯将自己的css样式优先级调高。

在级联css的情况下 这种情况更甚，这绝对会是一个灾难。

添加永远比删除来得要更为困难。

可维护性
```css
.nav { // your code
  border-shadow: 1px 1px 1px #ccc;
}
.otherPageNav { // my code
  border-shadwo: 1px 1px 1px #ccc;
}
```

这种添加是无休止的。这样的难以维护的情况下，你的css文件会越来越大，且相似代码会越来越多。

可扩展性
绝对追求的扩展性一定程度上也是灾难。
往后添加的css代码应该尽可能会**影响**原有单元的css代码。

可复用性
如何复用一段css代码？是将其按最小功能划分，还是按模块功能划分最小单元复用？

可读性
我们知道一段css属性众多，而且彼此影响，经常可能从脑中并不能直观地debug出实际的场景。
```css
div{
  border-radius: 6px;
}
.item div{
  border-left-radius: 3px;
}
.boxItem {
  border-radius: 3px;
}
```

---

社区几种**著名**方法

OOCSS

相信编程都听过OOP。封装继承多态。
旨在抽象最小单元进行继承复用。（当然OOP是一个很大的概念。）

在css中以差异找共通。

```
.wrapper {
  border-radius: 6px;
  height: auto;
}
```

---

占坑
